### ISSUE TITLE
Can't run tests with testinfra

### ISSUE THREAD

**Issue by arthurzenika** [mitodl/vault-formula#4]
```
[ERROR   ] Failed to import states testinframod, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1332, in _load_module
    ), fn_, fpath, desc)
  File "/var/cache/salt/minion/extmods/states/testinframod.py", line 65, in <module>
    _generate_functions()
  File "/var/cache/salt/minion/extmods/states/testinframod.py", line 55, in _generate_functions
    for module in modules.__all__:
AttributeError: 'module' object has no attribute '__all__'
[ERROR   ] State 'testinfra.file' was not found in SLS 'vault.tests.test_install'
Reason: 'testinfra.file' is not available.

[ERROR   ] State 'testinfra.file' was not found in SLS 'vault.tests.test_install'
Reason: 'testinfra.file' is not available.

[ERROR   ] State 'testinfra.file' was not found in SLS 'vault.tests.test_install'
Reason: 'testinfra.file' is not available.

[ERROR   ] State 'testinfra.service' was not found in SLS 'vault.tests.test_install'
Reason: 'testinfra.service' is not available.

[ERROR   ] State 'testinfra.file' was not found in SLS 'vault.tests.test_configure'
Reason: 'testinfra.file' is not available.
```

With testinfra==1.6.3

Not sure if I should file a bug at https://github.com/mitodl/salt-extensions

**Comment by blarghmatey** [comment]
@arthurlogilab that was from a bug in the testinfra extension and how it interfaced with the new (at the time) version of testinfra. I've patched the testinfra extension to support that version so, if you're still looking to run the tests it should be working now :)

**Comment by arthurzenika** [comment]
@blarghmatey thanks!
